apiVersion: v1
kind: Service
metadata:
  name: {{ include "void-observability.fullname" . }}-alertmanager
  labels:
    {{- include "void-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "void-observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
