apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "void-observability.fullname" . }}-alertmanager
  labels:
    {{- include "void-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "void-observability.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{- include "void-observability.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image }}:{{ .Values.alertmanager.tag }}"
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: 9093
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
      volumes:
        - name: config
          configMap:
            name: {{ include "void-observability.fullname" . }}-alertmanager
