apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "void-observability.fullname" . }}-mosquitto
  labels:
    {{- include "void-observability.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
