apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "void-observability.fullname" . }}-node-exporter
  labels:
    {{- include "void-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    matchLabels:
      {{- include "void-observability.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        {{- include "void-observability.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: node-exporter
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: node-exporter
          image: "{{ .Values.nodeExporter.image }}:{{ .Values.nodeExporter.tag }}"
          args:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)"
          ports:
            - containerPort: 9100
              name: http
              protocol: TCP
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
